### ISSUE TITLE
add Quick Look plugin for custom document format.

### ISSUE THREAD

**Issue by fespinoza** [fespinoza/linked-ideas-osx#34]
## TODO

- [ ] make new target for building the quicklook plugin
- [ ] copy over the files from the other xcode project
- [ ] configure build product of xcode project to be added inside the product of the mac app.
