### ISSUE TITLE
Improve input & rendering of strings in canvas

### ISSUE THREAD

**Issue by fespinoza** [fespinoza/linked-ideas-osx#35]
The input field should be aligned and expand as needed until a maximum size, after that it should expand down.

Within the frame that a input field is shown, the text should be drawn in the same way.

## TODO

- [x] add autoresizing text field.
  - [ ] solve sometimes weird expansion of textfield. problem described in [SO](http://stackoverflow.com/questions/43902740/strange-scrolling-on-nstextfield)
- [x] improve rendered area of text drawn.
- [x] consider drawing of selected markers
- [ ] refine positioning between rendered text and text field [SO 2](http://stackoverflow.com/questions/43922735/draw-nstextfield-setting-the-content-nsrect)
